<?php

return [
    [
        'title' => 'LimProject',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/LimProject',
    ],
    [
        'title' => 'htmlcss-hello',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/htmlcss-hello',
    ],
    [
        'title' => 'html-london-trip',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/html-london-trip',
    ],
    [
        'title' => 'html-css-booleaner',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/html-css-booleaner',
    ],
    [
        'title' => 'html-css-toboolist',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/html-css-toboolist',
    ],
    [
        'title' => 'html-css-float-cards',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/html-css-float-cards',
    ],
    [
        'title' => 'htmlcss-struttura-discord',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/htmlcss-struttura-discord',
    ],
    [
        'title' => 'htmlcss-discord',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/htmlcss-discord',
    ],
    [
        'title' => 'html-css-zoom',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/html-css-zoom',
    ],
    [
        'title' => 'html-css-animation-filter',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/html-css-animation-filter',
    ],
    [
        'title' => 'htmlcss-dropbox',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/htmlcss-dropbox',
    ],
    [
        'title' => 'html-css-resp-wannabe',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/html-css-resp-wannabe',
    ],
    [
        'title' => 'htmlcss-responsive-layout',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/htmlcss-responsive-layout',
    ],
    [
        'title' => 'html-css-spotifyweb',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/html-css-spotifyweb',
    ],
    [
        'title' => 'html-css-bootstrap-freelancer',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/html-css-bootstrap-freelancer',
    ],
    [
        'title' => 'html-css-bootstrap-dashboard',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/html-css-bootstrap-dashboard',
    ],
    [
        'title' => 'human-code',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/human-code',
    ],
    [
        'title' => 'js-pwdgen-wannabe',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-pwdgen-wannabe',
    ],
    [
        'title' => 'js-biglietto-treno',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-biglietto-treno',
    ],
    [
        'title' => 'js-mail-dadi',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-mail-dadi',
    ],
    [
        'title' => 'js-fizzbuzz',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-fizzbuzz',
    ],
    [
        'title' => 'js-array-carousel',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-array-carousel',
    ],
    [
        'title' => 'js-lista-spesa',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-lista-spesa',
    ],
    [
        'title' => 'js-biglietto-treno-form',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-biglietto-treno-form',
    ],
    [
        'title' => 'js-paliedispari',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-paliedispari',
    ],
    [
        'title' => 'js-campominato-grid',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-campominato-grid',
    ],
    [
        'title' => 'js-campominato-dom',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-campominato-dom',
    ],
    [
        'title' => 'js-our-team',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-our-team',
    ],
    [
        'title' => 'js-simon',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-simon',
    ],
    [
        'title' => 'js-array-objects-carousel',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-array-objects-carousel',
    ],
    [
        'title' => 'js-social-posts',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/js-social-posts',
    ],
    [
        'title' => 'vue-hello',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/vue-hello',
    ],
    [
        'title' => 'vue-slider',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/vue-slider',
    ],
    [
        'title' => 'vue-todolist',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/vue-todolist',
    ],
    [
        'title' => 'vue-boolzapp',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/vue-boolzapp',
    ],
    [
        'title' => 'vue-email-list',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/vue-email-list',
    ],
    [
        'title' => 'vite-hello-world',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/vite-hello-world',
    ],
    [
        'title' => 'vite-boolando',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/vite-boolando',
    ],
    [
        'title' => 'vite-yu-gi-oh',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/vite-yu-gi-oh',
    ],
    [
        'title' => 'vite-boolflix',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/vite-boolflix',
    ],
    [
        'title' => 'proj-html-vuejs',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/proj-html-vuejs',
    ],
    [
        'title' => 'php-badwords',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/php-badwords',
    ],
    [
        'title' => 'php-hotel',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/php-hotel',
    ],
    [
        'title' => 'php-strong-password-generator',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/php-strong-password-generator',
    ],
    [
        'title' => 'php-todo-list-json',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/php-todo-list-json',
    ],
    [
        'title' => 'php-oop-1',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/php-oop-1',
    ],
    [
        'title' => 'db-first',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/db-first',
    ],
    [
        'title' => 'db-university',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/db-university',
    ],
    [
        'title' => 'laravel-primi-passi',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/laravel-primi-passi',
    ],
    [
        'title' => 'laravel-boolando',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/laravel-boolando',
    ],
    [
        'title' => 'laravel-model-controller',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/laravel-model-controller',
    ],
    [
        'title' => 'laravel-migration-seeder',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/laravel-migration-seeder'
    ],
    [
        'title' => 'laravel-dc-comics',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/laravel-dc-comics'
    ],
    [
        'title' => 'laravel-auth',
        'description' => 'Descrizione del progetto 1',
        'start_date' => now(),
        'website_url' => 'https://github.com/Pirisinu/laravel-auth'
    ]

];
